START TRANSACTION;

CREATE DATABASE IF NOT EXISTS `migration_manager`;

USE `migration_manager`;

CREATE TABLE migrations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  db_name VARCHAR(255) NOT NULL,
  run_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  up TEXT NOT NULL,
  down TEXT NOT NULL
);

COMMIT;
